baseURL = "/"
languageCode = "en-us"
summaryLength = "10"
theme = "kross-hugo"
title = "OwlSec Technologies"
[[menu.main]]
URL = "about"
name = "About"
weight = 2
[[menu.main]]
URL = "blog"
name = "Blog"
weight = 3
[[menu.main]]
URL = "portfolio"
name = "Portfolio"
weight = 4
[[menu.main]]
URL = "contact"
name = "Contact"
weight = 5
[params]
address = "Nairobi, Kenya"
author = "OwlSec Technologies"
copyright = "Copyrighht &copy; 2020 [OwlSec Technologies](https://krossowlsec.netlify.app/)"
description = "OwlSec Technologies is a strategic I.T and Cybersecurity agency based in Nairobi, Kenya"
email = "info@owlsectechnologies.co.ke"
google_analitycs_id = ""
home = "Home"
logo = "images/logo.png"
phone = "+254 740 128 010"
theme_color = "#41228e"
[params.contact]
enable = true
form_action = "data-netlify=\"true\""
[[params.plugins.css]]
URL = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
URL = "plugins/slick/slick.css"
[[params.plugins.css]]
URL = "plugins/themify-icons/themify-icons.css"
[[params.plugins.js]]
URL = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
URL = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
URL = "plugins/slick/slick.min.js"
[[params.plugins.js]]
URL = "plugins/shuffle/shuffle.min.js"
[params.preloader]
enable = true
preloader = ""
[[params.social]]
URL = "https://www.facebook.com/owlsectech/"
icon = "ti-facebook"
[[params.social]]
URL = "https://www.instagram.com/owlsectech/?hl=en"
icon = "ti-instagram"
[[params.social]]
URL = "https://twitter.com/owlsectech"
icon = "ti-twitter-alt"
